# Exploratory Data Analysis (EDA)

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
#  Load the cleaned data sets from the data.Rmd
setwd(here::here("data/"))
game_results <- read_csv("game_results_cleaned.csv")
team_stats <- read_csv("team_stats_cleaned.csv")
players_stats <- read_csv("players_stats_cleaned.csv")
players_value_cleaned <- read_csv("players_value_cleaned.csv")
```

## Games Results

```{r}

```

```{r, echo=FALSE, warning= FALSE}
#Home Vs Away wins

```

```{r, echo=FALSE, warning=FALSE}
#Since the season is a fixed parameter (2006-2007), we can focus on the team players and the result  according to where the game happen.

home <- ggplot(data=game_results, aes(x=home_team, y=result, fill=result)) +
  geom_bar(stat="identity")+
  scale_fill_brewer(palette="Blues")+
  geom_text(aes(label=home_goals), vjust=1.6, color="white",
            position = position_dodge(0.9), size=3.5)
home

Resultat <- ggplot(data=game_results, aes(x=home_team, y=away_team)) +
  geom_point(aes(colour = factor(result)))

Resultat


```

<br>


## Players Stats



```{r, echo=FALSE}
#Ask TA if we should focus on teams or players
#to know who relatively has the highest wins percentage - we can remove this later if it will not help us with our EDA.
#Limitation: We do not have the number of minutes which each player played. Some of their appeaerences might include only 10 minutes and some might be 90 minutes but we do not have data that is that detailed.

win_percentage <- players_stats %>% mutate(Wins_Perc = Wins/Appearances, .after= Wins)

win_percentage_plot <- plot_ly(win_percentage, x = ~Name, y = ~Wins_Perc, type = 'bar', width = 1000, height = 600, color = ~Club ) %>%
  layout(title= 'Wins Percentage per Player' )

win_percentage_plot
```
<br>

```{r}
groupedby_club <- win_percentage [!is.na(win_percentage$Wins_Perc),]%>% group_by(Club) %>%  summarise(Wins_Perc_mean = mean(Wins_Perc ), Wins_Perc_median = median(Wins_Perc))

groupedbymean_club_plot <- plot_ly(groupedby_club, x = ~Club, y = ~Wins_Perc_mean, type = 'bar', width = 1000, height = 600, color = ~Club ) %>%
  layout(title= 'Wins Percentage Mean per Club' )

# groupedbymedian_club_plot <- plot_ly(groupedby_club, x = ~Club, y = ~Wins_Perc_median, type = 'bar', width = 1000, height = 600, color = ~Club ) %>%
#   layout(title= 'Wins Percentage Median per Club' )

groupedbymean_club_plot 

# groupedbymedian_club_plot

```


<br>

```{r, echo=FALSE}
 #to know who relatively scored the highest goals between the defenders. 

goals_defender <- players_stats %>% filter(Position == "Defender") %>% mutate(Goals_Perc = Goals/Appearances, .after= Goals)

goals_defender_plot <- plot_ly(goals_defender, x = ~Name, y = ~Goals_Perc, type = 'bar', name = ~Club, width = 1000, height = 600, color = ~Club ) %>%
  layout(title= 'Goals Percentage per Defender' )

goals_defender_plot
```

<br>

```{r, echo=FALSE}
#to know who relatively scored the highest goals between the Midfielder 

goals_midfielder <- players_stats %>% filter(Position == "Midfielder") %>% mutate(Goals_Perc = Goals/Appearances, .after= Goals) 

goals_midfielder_plot <- plot_ly(goals_midfielder, x = ~Name, y = ~Goals_Perc, type = 'bar', name = ~Club, width = 1000, height = 600 , color = ~Club) %>%
  layout(title= 'Goals Percentage per Midfielder' )

goals_midfielder_plot
```
<br>

```{r, echo=FALSE}
#to know who relatively scored the highest goals between the Forward 

goals_forward <- players_stats %>% filter(Position == "Forward") %>% mutate(Goals_Perc = Goals/Appearances, .after= Goals) 

goals_forward_plot <- plot_ly(goals_forward, x = ~Name, y = ~Goals_Perc, type = 'bar', name = ~Club, width = 1000, height = 600, color = ~Club ) %>%
  layout(title= 'Goals Percentage per Forward' )

goals_forward_plot
```

<br> 

```{r, echo=FALSE}
#Goals to Shots percentage for each forward player

goals_shots <- players_stats %>% filter(Position == "Forward") %>% mutate(goals_shots = Goals/Shots, .after= Goals) 

goals_shots_plot <- plot_ly(goals_shots, x = ~Name, y = ~goals_shots, type = 'bar', name = ~Club, width = 1000, height = 600, color = ~Club ) %>%
  layout(title= 'Goals/ Shots per Forward Player' )

goals_shots_plot
```

<br>

```{r, echo=FALSE}
#To check if age has any effect on the goals that players score
age_wins_corrplot <- plot(win_percentage$Age, win_percentage$Wins_Perc, main = "Age Vs Wins", pch = 19, col = "blue", xlab = "Age", ylab = "Percentage of Wins")
abline(lm(win_percentage$Wins_Perc~win_percentage$Age), col = "green", lwd = 3)

age_wins_corrplot

age_goals <- players_stats %>% mutate(Goals_Perc = Goals/Appearances, .after= Goals)
age_goals_corrplot <- plot(age_goals$Age, age_goals$Goals_Perc, main = "Age Vs Goals", pch = 19, col = "blue", xlab = "Age", ylab = "Percentage of Goals")
abline(lm(age_goals$Goals_Perc~age_goals$Age), col = "red", lwd = 3)

age_goals_corrplot

#Another way to do the scatter plot
# corrplottest<- plot_ly(win_percentage, x = ~Age, y = ~Wins_Perc , type = 'scatter', width = 1000, height = 600 ) 

#corrplottest
```

<br>
## Players Value




```{r, echo=FALSE}

```

<br>
## Team Stats

```{r, echo=FALSE}
# Just verifying we have all the data for the team stats for all the games of the season.

team_stats_verification <- team_stats %>% 
  group_by(season) %>% 
  mutate(number_of_team = n(), # number of team per season
         draw = (number_of_team-1)*2 - wins - losses, # draw is missing
         total = wins + losses + draw) %>%  # verifying the data
  select(team, wins, losses, draw, total, everything())

# Creating a dataset for the exploratory data analysis
team_stats_EDA <- team_stats_verification %>% 
  group_by(season) %>% 
  mutate(number_of_points = 3*wins + 1*draw)

team_stats %>%
  select(-c(team,season)) %>%
  cor()

str(team_stats_EDA)

# Too confusing, too much infos on one graph. Too small, not very helpful

# Correlation between points and goals?

team_stats_EDA %>% ggplot(aes(x=number_of_points, y=goals)) +
  geom_point() +
  geom_smooth(method='lm', ) +
  facet_wrap(. ~ season, ncol = 3)

# Obviously a nice correlation

# Yellow cards?

team_stats_EDA %>% ggplot(aes(x=number_of_points, y=total_yel_card)) +
  geom_point() +
  geom_smooth(method='lm', ) +
  facet_wrap(. ~ season, ncol = 3)

# No real correlation


```

```{r, echo=FALSE}
#wins and goals per team per season

team_stats_filtered <- team_stats %>% select(team, wins, losses, goals, season)

winsbyseason_plot <- plot_ly(team_stats_filtered, x = ~team, y = ~wins, type = 'bar', width = 1000, height = 600, color = ~season ) %>%
  layout(title= 'Wins by Seasons' )

goalsbyseason_plot <- plot_ly(team_stats_filtered, x = ~team, y = ~goals, type = 'bar', width = 1000, height = 600, color = ~season ) %>%
  layout(title= 'Goals by Seasons' )

winsbyseason_plot

goalsbyseason_plot
```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```

```{r, echo=FALSE}

```
