<style>
body {
text-align: justify}
</style>

<br>

# Conclusion

To conclude, we observe that for both supervised and unsupervised learning, variables that stand out the most and who are the most important are the ones related to goals and shots. This actually makes sense as they determine the final result. For supervised learning, they are important in order to predict the match result, and for clustering they characterize the different teams when they are either receiving or visiting.

It seems like the prediction of results can be done by extrapolating the data that can be obtained from the previous matches, otherwise we have to predict during the match according to data observed. This is often what betting websites do.

We could improve our 2 chosen machine learning models by including data on the specific characteristics of the players in these teams just like in “Moneyball”, whoever this could result in a very complex model. We unfortunately couldn’t find reliable and good enough data to do so, but it is our recommended idea for future works.

<br>
<br>
