# Exploratory Data Analysis (EDA)

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
#  Load the cleaned dataset from the data.Rmd
setwd(here::here("Data_New/"))
premier_league_results <- read_csv("premier_league_results_clean.csv")
```

## Premier League Results

##Single variable Analysis

```{r, echo=FALSE}
str(premier_league_results)
```

```{r}
# League_division
premier_league_results %>%
  select(league_division) %>% 
  ggplot(aes(x = league_division)) +
  geom_bar()

# Unique value - therefore we can remove the column league_division
```

```{r}
# match_date
premier_league_results %>% 
  select(match_date) %>% 
  ggplot(aes(x = year(match_date))) +
  geom_bar()

# Ok seems good for the repartition of the years
```

```{r}
# Home team
premier_league_results %>% 
  select(home_team) %>% 
  ggplot(aes(x = home_team)) +
  geom_bar()

# All good, same numbers
```
```{r}
# Home team
premier_league_results %>% 
  select(away_team) %>% 
  ggplot(aes(x = away_team)) +
  geom_bar()

# All good, same numbers
```

```{r}
# Full-time home goals
premier_league_results %>% 
  select(full_time_home_goals) %>% 
  ggplot(aes(x = full_time_home_goals)) +
  geom_boxplot() +
  xlim(0,8)

# half-time home goals
premier_league_results %>% 
  select(half_time_home_goals) %>% 
  ggplot(aes(x = half_time_home_goals)) +
  geom_boxplot()+
  xlim(0,5)

# Full-time against half-time - home team
premier_league_results %>% 
  select(full_time_home_goals, half_time_home_goals) %>% 
  ggplot(aes(x = full_time_home_goals, y = half_time_home_goals)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)

# Full-time away goals
premier_league_results %>% 
  select(full_time_away_goals) %>% 
  ggplot(aes(x = full_time_away_goals)) +
  geom_boxplot()+
  xlim(0,8)

# half-time away goals
premier_league_results %>% 
  select(half_time_away_goals) %>% 
  ggplot(aes(x = half_time_away_goals)) +
  geom_boxplot()+
  xlim(0,5)

# Full-time against half-time - away team

premier_league_results %>% 
  select(full_time_away_goals, half_time_away_goals) %>% 
  ggplot(aes(x = full_time_away_goals, y = half_time_away_goals)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)
```
```{r}
# full-time results
premier_league_results %>% 
  select(full_time_results) %>% 
  ggplot(aes(x = full_time_results)) +
  geom_bar()

# half-time results
premier_league_results %>% 
  select(half_time_results) %>% 
  ggplot(aes(x = half_time_results)) +
  geom_bar()
```

```{r}
# referee
premier_league_results %>% 
  select(referee) %>% 
  ggplot(aes(x = referee)) +
  geom_bar()

# Ok not interesting, except if we say that referees are corrupted :)
```
```{r}
# home shots
premier_league_results %>% 
  select(home_shots) %>% 
  ggplot(aes(x = home_shots)) +
  geom_boxplot() +
  xlim(0,40)

# home shots on target
premier_league_results %>% 
  select(home_shots_ontarget) %>% 
  ggplot(aes(x = home_shots_ontarget)) +
  geom_boxplot() +
  xlim(0,40)

# shots versus on target
premier_league_results %>% 
  select(home_shots, home_shots_ontarget) %>% 
  ggplot(aes(x = home_shots, y = home_shots_ontarget)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)
```
```{r}
# away shots
premier_league_results %>% 
  select(away_shots) %>% 
  ggplot(aes(x = away_shots)) +
  geom_boxplot() +
  xlim(0,40)

# away shots on target
premier_league_results %>% 
  select(away_shots_ontarget) %>% 
  ggplot(aes(x = away_shots_ontarget)) +
  geom_boxplot() +
  xlim(0,40)

# shots versus on target
premier_league_results %>% 
  select(away_shots, away_shots_ontarget) %>% 
  ggplot(aes(x = away_shots, y = away_shots_ontarget)) +
  geom_point() +
  geom_abline(intercept = 0, slope = 1)
```

```{r}
# fouls
premier_league_results %>% 
  select(home_fouls) %>% 
  ggplot(aes(x = home_fouls)) +
  geom_boxplot() +
  xlim(0,30)

premier_league_results %>% 
  select(away_fouls) %>% 
  ggplot(aes(x = away_fouls)) +
  geom_boxplot() +
  xlim(0,30)
```
```{r}
# corners
premier_league_results %>% 
  select(home_corners) %>% 
  ggplot(aes(x = home_corners)) +
  geom_boxplot() +
  xlim(0,20)

premier_league_results %>% 
  select(away_corners) %>% 
  ggplot(aes(x = away_corners)) +
  geom_boxplot() +
  xlim(0,20)
```
```{r}
# yellow cards
premier_league_results %>% 
  select(home_yellow_cards) %>% 
  ggplot(aes(x = home_yellow_cards)) +
  geom_boxplot() +
  xlim(0,8)

premier_league_results %>% 
  select(away_yellow_cards) %>% 
  ggplot(aes(x = away_yellow_cards)) +
  geom_boxplot() +
  xlim(0,8)
```

```{r}
# red cards
premier_league_results %>% 
  select(home_red_cards) %>% 
  ggplot(aes(x = home_red_cards)) +
  geom_boxplot()

premier_league_results %>% 
  select(away_red_cards) %>% 
  ggplot(aes(x = away_red_cards)) +
  geom_boxplot()
```

```{r}
# betting website - bet365
premier_league_results %>% 
  select(bet365_home_win_odds) %>% 
  ggplot(aes(x = bet365_home_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(bet365_away_win_odds) %>% 
  ggplot(aes(x = bet365_away_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(bet365_draw_odds) %>% 
  ggplot(aes(x = bet365_draw_odds)) +
  geom_boxplot()
```
```{r}
# betting website - bet&win
premier_league_results %>% 
  select(`bet&win_home_win_odds`) %>% 
  ggplot(aes(x = `bet&win_home_win_odds`)) +
  geom_boxplot()

premier_league_results %>% 
  select(`bet&win_away_win_odds`) %>% 
  ggplot(aes(x = `bet&win_away_win_odds`)) +
  geom_boxplot()

premier_league_results %>% 
  select(`bet&win_draw_odds`) %>% 
  ggplot(aes(x = `bet&win_draw_odds`)) +
  geom_boxplot()
```

```{r}
# betting website - interwetten
premier_league_results %>% 
  select(interwetten_home_win_odds) %>% 
  ggplot(aes(x = interwetten_home_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(interwetten_away_win_odds) %>% 
  ggplot(aes(x = interwetten_away_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(interwetten_draw_odds) %>% 
  ggplot(aes(x = interwetten_draw_odds)) +
  geom_boxplot()
```
```{r}
# betting website - pinnacle
premier_league_results %>% 
  select(pinnacle_home_win_odds) %>% 
  ggplot(aes(x = pinnacle_home_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(pinnacle_away_win_odds) %>% 
  ggplot(aes(x = pinnacle_away_win_odds)) +
  geom_boxplot()

premier_league_results %>% 
  select(pinnacle_draw_odds) %>% 
  ggplot(aes(x = pinnacle_draw_odds)) +
  geom_boxplot()
```


## Multivariate Analysis


### Premiere League Results 2017-2018

```{r, echo=FALSE}
PLR17 <- premier_league_results %>% filter(match_date <= as.Date("2018-05-13"))	
```

```{r, echo=FALSE}
data_frame(PLR17$full_time_home_goals, PLR17$full_time_away_goals, PLR17$full_time_results, PLR17$home_shots, PLR17$away_shots, PLR17$home_fouls, PLR17$away_fouls, PLR17$home_yellow_cards, PLR17$away_yellow_cards, PLR17$home_red_cards, PLR17$away_red_cards) %>%
  plot_histogram(ncol = 3)
```



```{r, echo=FALSE}
data_frame(PLR17$full_time_home_goals, PLR17$full_time_away_goals, PLR17$full_time_results, PLR17$home_shots, PLR17$away_shots, PLR17$home_fouls, PLR17$away_fouls, PLR17$home_yellow_cards, PLR17$away_yellow_cards, PLR17$home_red_cards, PLR17$away_red_cards) %>%
  plot_density(ncol = 3)
```

```{r, echo=FALSE}
#not sure if we should keep this
data_frame(PLR17$full_time_home_goals, PLR17$full_time_away_goals, PLR17$full_time_results, PLR17$home_shots, PLR17$away_shots, PLR17$home_fouls, PLR17$away_fouls, PLR17$home_yellow_cards, PLR17$away_yellow_cards, PLR17$home_red_cards, PLR17$away_red_cards) %>%
  plot_correlation()
```

```{r, echo=FALSE}
PLR17 %>%
  group_by(home_team, full_time_results) %>% summarise(counts = n(), .groups = 'drop') %>%
  plot_ly(x = ~home_team, y = ~counts, type = 'bar', color = ~full_time_results, height = 500, width = 1000) %>%
  layout(title= 'Number of wins when Home 17-18', barmode = 'stack' )
```


```{r, echo=FALSE}
# to discuss which type to keep
PLR17 %>%
  group_by(away_team, full_time_results) %>% summarise(counts = n(), .groups = 'drop') %>%
  plot_ly(x = ~away_team, y = ~counts, type = 'bar', color = ~full_time_results, height = 500, width = 1000) %>%
  layout(title= 'Number of wins when Away 17-18', barmode = 'group' )
```


```{r}
ggplot(PLR17, aes(x = full_time_home_goals, y = home_team, fill = home_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```


```{r}
ggplot(PLR17, aes(x = full_time_away_goals, y = away_team, fill = away_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```


### Premiere League Results 2017-2018


```{r, echo=FALSE}
PLR18 <- premier_league_results %>% filter(match_date > as.Date("2018-05-13"))
```

```{r, echo=FALSE}
data_frame(PLR18$full_time_home_goals, PLR18$full_time_away_goals, PLR18$full_time_results, PLR18$home_shots, PLR18$away_shots, PLR18$home_fouls, PLR18$away_fouls, PLR18$home_yellow_cards, PLR18$away_yellow_cards, PLR18$home_red_cards, PLR18$away_red_cards) %>%
  plot_histogram(ncol = 3)
```


```{r, echo=FALSE}
data_frame(PLR18$full_time_home_goals, PLR18$full_time_away_goals, PLR18$full_time_results, PLR18$home_shots, PLR18$away_shots, PLR18$home_fouls, PLR18$away_fouls, PLR18$home_yellow_cards, PLR18$away_yellow_cards, PLR18$home_red_cards, PLR18$away_red_cards) %>%
  plot_density(ncol = 3)
```

```{r, echo=FALSE}
data_frame(PLR18$full_time_home_goals, PLR18$full_time_away_goals, PLR18$full_time_results, PLR18$home_shots, PLR18$away_shots, PLR18$home_fouls, PLR18$away_fouls, PLR18$home_yellow_cards, PLR18$away_yellow_cards, PLR18$home_red_cards, PLR18$away_red_cards) %>%
  plot_correlation()
```


```{r, echo=FALSE}
PLR18 %>%
  group_by(home_team, full_time_results) %>% summarise(counts = n(), .groups = 'drop') %>%
  plot_ly(x = ~home_team, y = ~counts, type = 'bar', color = ~full_time_results, height = 500, width = 1000) %>%
  layout(title= 'Number of wins when Home 18-19', barmode = 'stack' )
```


```{r, echo=FALSE}
PLR18 %>%
  group_by(away_team, full_time_results) %>% summarise(counts = n(), .groups = 'drop') %>%
  plot_ly(x = ~away_team, y = ~counts, type = 'bar', color = ~full_time_results, height = 500, width = 1000) %>%
  layout(title= 'Number of wins when Away 18-19', barmode = 'stack' )
```



```{r}
ggplot(PLR18, aes(x = full_time_home_goals, y = home_team, fill = home_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```


```{r}
ggplot(PLR18, aes(x = full_time_away_goals, y = away_team, fill = away_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```


#Premiere League Results


```{r, echo=FALSE}
#might remove
data_frame(premier_league_results$full_time_home_goals, premier_league_results$full_time_away_goals, premier_league_results$full_time_results, premier_league_results$home_shots, premier_league_results$away_shots, premier_league_results$home_fouls, premier_league_results$away_fouls, premier_league_results$home_yellow_cards, premier_league_results$away_yellow_cards, premier_league_results$home_red_cards, premier_league_results$away_red_cards) %>%
  plot_histogram(ncol = 3)
```





```{r, echo=FALSE}
#might remove
data_frame(premier_league_results$full_time_home_goals, premier_league_results$full_time_away_goals, premier_league_results$full_time_results, premier_league_results$home_shots, premier_league_results$away_shots, premier_league_results$home_fouls, premier_league_results$away_fouls, premier_league_results$home_yellow_cards, premier_league_results$away_yellow_cards, premier_league_results$home_red_cards, premier_league_results$away_red_cards) %>%
  plot_density(ncol = 3)
```


```{r, echo=FALSE}
#might remove
data_frame(premier_league_results$full_time_home_goals, premier_league_results$full_time_away_goals, premier_league_results$home_shots, premier_league_results$away_shots, premier_league_results$home_fouls, premier_league_results$away_fouls, premier_league_results$home_yellow_cards, premier_league_results$away_yellow_cards, premier_league_results$home_red_cards, premier_league_results$away_red_cards) %>%
  plot_correlation()
```

```{r}
ggplot(premier_league_results, aes(x = full_time_home_goals, y = home_team, fill = home_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```
```{r}
ggplot(premier_league_results, aes(x = full_time_away_goals, y = away_team, fill = away_team)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```



