# Unsupervised Learning

```{r, echo = FALSE, message = FALSE}
source(here::here("scripts/setup.R"))
```

## Splitting of Dataset

```{r, echo=FALSE}
setwd(here::here("Data_New/"))
premier_league_results <- read_csv("premier_league_results_clean.csv")
```

```{r, echo=FALSE}
# Divide the dataset into Home and Away

PLR_Home <- premier_league_results %>% select(home_team, full_time_home_goals, half_time_home_goals, home_shots, home_shots_ontarget, home_fouls, home_corners, home_yellow_cards, home_red_cards)

PLR_Away <- premier_league_results %>% select (away_team, full_time_away_goals, half_time_away_goals, away_shots, away_shots_ontarget, away_fouls, away_corners, away_yellow_cards, away_red_cards)
```

```{r}
# Group by teams

PLR_Home <- PLR_Home %>% group_by(home_team) %>% 
  summarise(mean_full_time_home_goals = mean(full_time_home_goals), 
            mean_half_time_home_goals = mean(half_time_home_goals), 
            mean_home_shots = mean(home_shots),
            mean_home_shots_ontarget = mean(home_shots_ontarget),
            mean_home_fouls = mean(home_fouls),
            mean_home_corners = mean(home_corners),
            mean_home_yellow_cards = mean(home_yellow_cards),
            mean_home_red_cards = mean(home_red_cards), .groups = 'drop')


PLR_Away <- PLR_Away %>% group_by(away_team) %>% 
  summarise(mean_full_time_away_goals = mean(full_time_away_goals), 
            mean_half_time_away_goals = mean(half_time_away_goals), 
            mean_away_shots = mean(away_shots),
            mean_away_shots_ontarget = mean(away_shots_ontarget),
            mean_away_fouls = mean(away_fouls),
            mean_away_corners = mean(away_corners),
            mean_away_yellow_cards = mean(away_yellow_cards),
            mean_away_red_cards = mean(away_red_cards), .groups = 'drop')
```


## Clustering

```{r, echo=FALSE}

# Scale features for home and away

PLR_Home_Scale <- scale(PLR_Home[,-1]) %>% as_tibble()
PLR_Away_Scale <- scale(PLR_Away[,-1]) %>% as_tibble()


PLR_Home_Scale <- PLR_Home_Scale %>% 
  mutate(home_team = PLR_Home$home_team, .before = mean_full_time_home_goals )

PLR_Away_Scale <- PLR_Away_Scale %>% 
  mutate(away_team = PLR_Away$away_team, .before = mean_full_time_away_goals )

```



```{r, echo=FALSE}

# matrix of Manhattan distances 
PLR_Home_Mdistance <- dist(PLR_Home_Scale[,], method = "manhattan")

PLR_Away_Mdistance <- dist(PLR_Away_Scale[,], method = "manhattan")


#MIGHT DELETE THIS

# create a data frame of the distances in long format 
PLR_Home_melt <- melt(as.matrix(PLR_Home_Mdistance))
PLR_Away_melt <- melt(as.matrix(PLR_Away_Mdistance))

head(PLR_Home_melt)
head(PLR_Away_melt)

ggplot(data = PLR_Home_melt, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
ggplot(data = PLR_Away_melt, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()
```

```{r, echo=FALSE}
#code to try to change the labels
#dendrogram using a complete linkage for home and away

PLR_Home_hc <- hclust(PLR_Home_Mdistance, method = "complete")
plot(PLR_Home_hc, hang=-1) %>% set("labels", c("Burnley", "West Ham", "Everton", "New Castle", "Leicester", "Bournemouth", "Southampton", "Watford", "Brighton", "Huddersfield", "Arsenal", "Crystal Palace", "Man United", "Liverpool", "Man City", "Chelsea", "Tottenham")) %>% labels

#dend <- PLR_Home_hc %>% dist %>% hclust("ave") %>% as.dendrogram

# dend <- PLR_Home_hc %>% 
#        select(mean_full_time_home_goals , 
#             mean_half_time_home_goals, 
#             mean_home_shots,
#             mean_home_shots_ontarget,
#             mean_home_fouls,
#             mean_home_corners,
#             mean_home_yellow_cards,
#             mean_home_red_cards)%>% 
#   dist() %>% 
#   hclust() %>% 
#   as.dendrogram() 


PLR_Away_hc <- hclust(PLR_Away_Mdistance, method = "complete")
plot(PLR_Away_hc, hang=-1)

# labels(PLR_Home_hc) <- c("Burnley", "West Ham", "Everton", "New Castle", "Leicester", "Bournemouth", "Southampton", "Watford", "Brighton", "Huddersfield", "Arsenal", "Crystal Palace", "Man United", "Liverpool", "Man City", "Chelsea", "Tottenham")

#labels(PLR_Home_hc)

#dend <- hclust("complete") %>% as.dendrogram

 # PLR_Home_hc %>% set("labels", c("Burnley", "West Ham", "1B31", "4C31", "2C31", "4A31", "2B31", "1A31", "3B31", "3C31", "3A31", "4B31")) %>% plot(main="Dendrogram day 42")
```

```{r, echo=FALSE}
#We cut the tree to 4 clusters, and represent the result.
#We also extract the cluster assignment of each wine.
#
# plot(PLR_Home_hc, hang=-1)
# rect.hclust(PLR_Home_hc, k=4)
# PLR_Home_clust <- cutree(PLR_Home_hc, k=4)
# PLR_Home_clust
# 
# 
# fviz_nbclust(PLR_Home_Scale,
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "wss", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(PLR_Home_Scale,
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "silhouette", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(PLR_Home_Scale,
#              hcut, hc_method="complete",
#              hc_metric="manhattan",
#              method = "gap", 
#              k.max = 25, verbose = FALSE)
# #K-means
# fviz_nbclust(PLR_Home_Scale,
#              kmeans,
#              method = "wss", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(PLR_Home_Scale,
#              kmeans, 
#              method = "silhouette", 
#              k.max = 25, verbose = FALSE)
# fviz_nbclust(PLR_Home_Scale,
#              kmeans,
#              method = "gap", 
#              k.max = 25, verbose = FALSE)
# 
# PLR_kmeans <- kmeans(PLR_Home_Scale, centers=2)
# PLR.kmeans$cluster
```


## PCA

```{r, echo=FALSE}
# PLR.numeric <- premier_league_results %>% dplyr::select(where(is.numeric))
# PLR.pca <- PCA(PLR.numeric, ncp = 11, graph = FALSE)
# 
# PLR.pca

PLR_Home_numeric <- PLR_Home %>% dplyr::select(where(is.numeric)) 
PLR_Away_numeric <- PLR_Away %>% dplyr::select(where(is.numeric)) 

PLR_Home_pca <- PCA(PLR_Home_numeric, ncp = 11, graph = FALSE)
PLR_Away_pca <- PCA(PLR_Away_numeric, ncp = 11, graph = FALSE)

PLR_Home_pca
PLR_Away_pca
```

```{r, echo=FALSE}
fviz_pca_var(PLR_Home_pca)
fviz_pca_var(PLR_Away_pca)
```


```{r, echo=FALSE}
# Extract the contributions of each features in the dimension.
fviz_contrib(PLR_Home_pca, choice = "var", axes = 1) #aes determines which dimension
fviz_contrib(PLR_Away_pca, choice = "var", axes = 1)
```

```{r, echo=FALSE}
fviz_pca_ind(PLR_Home_pca) ## only the individuals
fviz_pca_ind(PLR_Away_pca)

fviz_pca_biplot(PLR_Home_pca) ## biplot
fviz_pca_biplot(PLR_Away_pca)
```


```{r, echo=FALSE}
fviz_eig(PLR_Home_pca, addlabels = TRUE, ncp=11)
fviz_eig(PLR_Away_pca, addlabels = TRUE, ncp=11)
```


```{r, echo=FALSE}
p1 <- fviz_pca_biplot(PLR_Home_pca, axes = 1:2) 
p2 <- fviz_pca_biplot(PLR_Home_pca, axes = 3:4) 
p3 <- fviz_pca_biplot(PLR_Home_pca, axes = 5:6) 
grid.arrange(p1, p2, p3, nrow = 2, ncol=2)

p4 <- fviz_pca_biplot(PLR_Away_pca, axes = 1:2) 
p5 <- fviz_pca_biplot(PLR_Away_pca, axes = 3:4) 
p6 <- fviz_pca_biplot(PLR_Away_pca, axes = 5:6) 
grid.arrange(p4, p5, p6, nrow = 2, ncol=2)
```

```{r, echo=FALSE}
PLR_Home_hc2 <- hclust(dist(PLR_Home, method = "manhattan"))
PLR_Away_hc2 <- hclust(dist(PLR_Away, method = "manhattan"))

PLR_Home_clust <- cutree(PLR_Home_hc2, k = 4)
PLR_Away_clust <- cutree(PLR_Away_hc2, k = 4)

fviz_pca_biplot(PLR_Home_pca,
             col.ind = factor(PLR_Home_clust))
fviz_pca_biplot(PLR_Away_pca,
             col.ind = factor(PLR_Away_clust))
```

## Unsupervised Learning Findings

xxx